# Generated by Django 2.1.4 on 2019-07-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JumpServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default=None, help_text='用户名', max_length=255, null=True, verbose_name='用户名')),
                ('ip', models.CharField(default=None, help_text='主机ip', max_length=255, null=True, verbose_name='主机ip')),
                ('hostname', models.CharField(default=None, help_text='主机名称', max_length=255, null=True, verbose_name='主机名称')),
                ('rank', models.CharField(choices=[(1, 'root'), (2, 'admin'), (3, 'rd')], db_column='yum_cpmpang', help_text='用户等级', max_length=255, null=True, verbose_name='用户等级')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('status', models.IntegerField(choices=[(1, '用户申请'), (2, '管理员审核')], default=1, help_text='状态', verbose_name='状态')),
            ],
            options={
                'db_table': 'zto_jumpserver',
            },
        ),
    ]
