# Generated by Django 2.1.3 on 2019-04-29 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_column='product_name', db_index=True, help_text='产品名', max_length=255, verbose_name='产品名')),
                ('description', models.CharField(db_column='description', help_text='描述', max_length=255, null=True, verbose_name='描述')),
            ],
            options={
                'db_table': 'zto_products',
                'ordering': ['id'],
            },
        ),
    ]
