# Generated by Django 2.1.3 on 2019-04-29 02:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='user',
            field=models.ManyToManyField(help_text='产品负责人', related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='产品负责人'),
        ),
    ]
