# Generated by Django 2.1.3 on 2019-05-24 08:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(db_column='project_name', default=None, help_text='项目名', max_length=255, verbose_name='项目名')),
                ('desc', models.CharField(db_column='description', help_text='服务描述', max_length=255, null=True, verbose_name='项目描述')),
                ('audit_user', models.ManyToManyField(db_column='audit_user', help_text='审核人', related_name='audit_user', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
                ('dev_user', models.ManyToManyField(db_column='dev_user', help_text='开发人', related_name='dev_user', to=settings.AUTH_USER_MODEL, verbose_name='开发人')),
                ('release_user', models.ManyToManyField(db_column='release_user', help_text='发布人', related_name='release_user', to=settings.AUTH_USER_MODEL, verbose_name='发布人')),
            ],
            options={
                'db_table': 'zto_project',
            },
        ),
    ]
