# Generated by Django 2.1.3 on 2019-05-27 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='desc',
            field=models.TextField(db_column='description', help_text='服务描述', max_length=2550, null=True, verbose_name='项目描述'),
        ),
    ]
