# Generated by Django 2.1.3 on 2019-05-28 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('publish', '0002_auto_20190527_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deploy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, help_text='项目名称', max_length=40, verbose_name='项目名称')),
                ('version', models.CharField(default=None, help_text='上线版本', max_length=40, verbose_name='上线版本')),
                ('info', models.TextField(help_text='版本描述', null=True, verbose_name='版本描述')),
                ('status', models.IntegerField(choices=[(0, '申请'), (1, '审核'), (2, '发布'), (4, '取消上线')], default=0, help_text='上线状态', verbose_name='上线状态')),
                ('release_status', models.IntegerField(choices=[(0, '发布成功'), (1, '发布失败'), (2, '终止发布')], help_text='发布完成状态', null=True, verbose_name='发布完成状态')),
                ('console_output', models.TextField(help_text='jenkins控制台输出的结果', null=True, verbose_name='上线输出结果')),
                ('apply_time', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('deploy_time', models.DateTimeField(auto_now=True, verbose_name='上线完成时间')),
                ('applicant', models.ForeignKey(help_text='申请人', on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to=settings.AUTH_USER_MODEL, verbose_name='申请人')),
                ('assign_to', models.ForeignKey(help_text='上线人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned', to=settings.AUTH_USER_MODEL, verbose_name='上线人')),
                ('reviewer', models.ForeignKey(help_text='审核人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer', to=settings.AUTH_USER_MODEL, verbose_name='审核人')),
            ],
        ),
    ]
