# Generated by Django 2.1.3 on 2019-05-28 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_deploy'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deploy',
            table='zto_deploy',
        ),
    ]
