# Generated by Django 2.1.3 on 2019-05-29 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_auto_20190528_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deploy',
            old_name='name',
            new_name='project_name',
        ),
    ]
