# Generated by Django 2.1.3 on 2019-05-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_auto_20190529_2106'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deploy',
            options={'ordering': ['-id']},
        ),
    ]
