# Generated by Django 2.1.3 on 2019-06-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_auto_20190529_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='release_status',
            field=models.IntegerField(choices=[(1, '发布成功'), (2, '发布失败'), (3, '终止发布')], help_text='发布完成状态', null=True, verbose_name='发布完成状态'),
        ),
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(1, '申请'), (2, '审核'), (3, '发布'), (4, '取消上线')], default=0, help_text='上线状态', verbose_name='上线状态'),
        ),
    ]
