# Generated by Django 2.1.3 on 2019-06-19 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0008_auto_20190610_2056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(1, '申请'), (2, '审核'), (3, '发布'), (4, '取消上线')], default=1, help_text='上线状态', verbose_name='上线状态'),
        ),
    ]
