# Generated by Django 2.1.3 on 2019-07-11 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0009_auto_20190619_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deploy',
            name='status',
            field=models.IntegerField(choices=[(1, '申请'), (2, '审核'), (3, '正在发布'), (4, '发布完成')], default=1, help_text='上线状态', verbose_name='上线状态'),
        ),
    ]
