# Generated by Django 2.1.3 on 2019-04-29 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('business', '0001_initial'),
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='product',
            field=models.ForeignKey(help_text='所属产品', null=True, on_delete=django.db.models.deletion.CASCADE, to='business.Products', verbose_name='所属产品'),
        ),
    ]
