# Generated by Django 2.1.3 on 2019-04-29 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_servers_product'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servers',
            name='user',
            field=models.ForeignKey(help_text='所属用户', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_servers', to=settings.AUTH_USER_MODEL, verbose_name='所属用户'),
        ),
    ]
