# Generated by Django 2.1.3 on 2019-06-20 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_servers_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='district',
            field=models.CharField(choices=[('深圳', 'shenzhen'), ('上海', 'shanghai')], db_column='district', help_text='地区', max_length=255, null=True, verbose_name='地区'),
        ),
    ]
