# Generated by Django 2.1.3 on 2019-07-22 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0004_auto_20190620_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servers',
            name='district',
            field=models.CharField(choices=[('上海', 'shanghai'), ('深圳', 'shenzhen')], db_column='district', help_text='地区', max_length=255, null=True, verbose_name='地区'),
        ),
    ]
