# Generated by Django 2.1.3 on 2019-07-17 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Workorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_name', models.CharField(db_column='work_name', default=None, help_text='报警名称', max_length=255, verbose_name='报警名称')),
                ('content', models.CharField(db_column='content', default=None, help_text='content', max_length=255, verbose_name='报警内容')),
                ('info', models.TextField(help_text='版本描述', null=True, verbose_name='版本描述')),
                ('status', models.IntegerField(choices=[(1, '待处理'), (2, '完成')], default=1, help_text='处理状态', verbose_name='处理状态')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='发生时间')),
                ('stop_time', models.DateTimeField(auto_now=True, verbose_name='完成时间')),
                ('manager_user', models.ForeignKey(help_text='处理人', on_delete=django.db.models.deletion.CASCADE, related_name='manager_user', to=settings.AUTH_USER_MODEL, verbose_name='处理人')),
            ],
            options={
                'db_table': 'zto_workorder',
                'ordering': ['-id'],
            },
        ),
    ]
