# Generated by Django 2.1.3 on 2019-07-17 09:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20190717_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='manager_user',
            field=models.ForeignKey(help_text='处理人', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managerUser', to=settings.AUTH_USER_MODEL, verbose_name='处理人'),
        ),
    ]
